version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dragons_development
      POSTGRES_USER: finch
      POSTGRES_PASSWORD: password

    volumes: 
      - db:/var/lib/postgresql/data
  web:
    environment: 
      RAILS_ENV: development
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/dragons
      - node_modules:/var/www/dragons/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
    driver: local
  node_modules:
    driver: local